"""init migrate

Revision ID: c61e11b51c8a
Revises: 
Create Date: 2017-12-14 21:35:30.955555

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c61e11b51c8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movieinfo', sa.Column('direcotr', sa.String(length=500), nullable=True))
    op.drop_index('ix_movieinfo_country', table_name='movieinfo')
    op.drop_index('ix_movieinfo_director', table_name='movieinfo')
    op.drop_index('ix_movieinfo_name', table_name='movieinfo')
    op.drop_index('ix_movieinfo_type', table_name='movieinfo')
    op.drop_column('movieinfo', 'director')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movieinfo', sa.Column('director', mysql.VARCHAR(length=500), nullable=True))
    op.create_index('ix_movieinfo_type', 'movieinfo', ['type'], unique=False)
    op.create_index('ix_movieinfo_name', 'movieinfo', ['name'], unique=False)
    op.create_index('ix_movieinfo_director', 'movieinfo', ['director'], unique=False)
    op.create_index('ix_movieinfo_country', 'movieinfo', ['country'], unique=False)
    op.drop_column('movieinfo', 'direcotr')
    # ### end Alembic commands ###
